<?php
declare(strict_types=1);
require __DIR__ . '/includes/bootstrap.php';
$user=current_user();$uid=$user?(int)$user['id']:0;$pdo=db();
$id=(int)($_GET['id']??0);$st=$pdo->prepare('SELECT * FROM questoes WHERE id=? AND ativo=1');$st->execute([$id]);$q=$st->fetch();
if(!$q || !question_is_public_ready($q)){$title='Questão não disponível';$active='questoes';include __DIR__.'/includes/header.php';echo '<div class="card"><p>Esta questão está indisponível no momento porque o texto extraído está incompleto ou em revisão. <a href="'.e(url('questoes.php')).'">Voltar ao banco</a></p></div>';include __DIR__.'/includes/footer.php';exit;}
$alts=q_alternativas($q);$nonEmpty=array_values(array_filter($alts,static fn($a)=>trim((string)$a)!==''));$gab=(int)$q['gabarito'];$gradable=$gab>=0&&$gab<=4&&count($nonEmpty)>=2;$answerable=count($nonEmpty)>=2;
$ultima=null;$fav=false;if($uid){$m=user_answers_map($uid,[(int)$q['id']]);$ultima=$m[(int)$q['id']]??null;$st=$pdo->prepare('SELECT 1 FROM favoritos WHERE user_id=? AND questao_id=?');$st->execute([$uid,$q['id']]);$fav=(bool)$st->fetchColumn();}
$st=$pdo->prepare('SELECT COUNT(*) t,COALESCE(SUM(correta),0) c FROM respostas WHERE questao_id=? AND avaliavel=1');$st->execute([$q['id']]);$qs=$st->fetch();
$st=$pdo->prepare('SELECT c.*,u.nome FROM comentarios c JOIN users u ON u.id=c.user_id WHERE c.questao_id=? AND c.aprovado=1 ORDER BY c.id DESC LIMIT 30');$st->execute([$q['id']]);$comments=$st->fetchAll();

// Simulado persistente 2.5.
$simId=(int)($_GET['sim_id']??0);$simPos=max(0,(int)($_GET['pos']??0));$sim=null;$simIds=[];$simAnswers=[];$nextId=null;$prevId=null;
if($simId>0&&$uid){$st=$pdo->prepare('SELECT * FROM simulados_execucoes WHERE id=? AND user_id=?');$st->execute([$simId,$uid]);$sim=$st->fetch();if($sim){$simIds=json_decode((string)$sim['ids_json'],true)?:[];$simIds=array_values(array_map('intval',$simIds));if(isset($simIds[$simPos+1]))$nextId=$simIds[$simPos+1];if($simPos>0&&isset($simIds[$simPos-1]))$prevId=$simIds[$simPos-1];$st=$pdo->prepare('SELECT questao_id,correta,avaliavel FROM simulado_respostas WHERE execucao_id=?');$st->execute([$simId]);foreach($st->fetchAll() as $r)$simAnswers[(int)$r['questao_id']]=$r;}}
if(!$sim){$simId=0;if($uid){$st=$pdo->prepare('SELECT id FROM questoes WHERE ativo=1 AND concurso=? AND id!=? AND NOT EXISTS (SELECT 1 FROM respostas r WHERE r.user_id=? AND r.questao_id=questoes.id) LIMIT 50');$st->execute([$q['concurso'],$q['id'],$uid]);}else{$st=$pdo->prepare('SELECT id FROM questoes WHERE ativo=1 AND concurso=? AND id!=? LIMIT 50');$st->execute([$q['concurso'],$q['id']]);}$cand=$st->fetchAll(PDO::FETCH_COLUMN);if($cand)$nextId=(int)$cand[array_rand($cand)];}

$pv=null;if((int)($q['exibir_preview']??0)===1&&!empty($q['origem'])&&(int)($q['pagina']??0)>0&&preg_match('/^(\d*\.?\d+)-(\d*\.?\d+)$/',(string)($q['regiao']??''),$mm)){$base=basename((string)$q['origem']);if(is_file(APP_ROOT.'/simulados/'.$base))$pv=['url'=>url('simulados/'.rawurlencode($base)),'page'=>(int)$q['pagina'],'y0'=>(float)$mm[1],'y1'=>(float)$mm[2]];}
$isOfficial=str_starts_with((string)$q['slug'],'oficial-');$enunciadoHtml=$isOfficial?nl2br(e((string)$q['enunciado'])):(string)$q['enunciado'];
$title=concurso_nome((string)$q['concurso']).' '.(int)$q['ano'].' · '.$q['materia'];$active='questoes';$extra_js='<script type="module" src="'.e(url('assets/js/question-previews.js?v='.rawurlencode(APP_VERSION))).'"></script>';include __DIR__.'/includes/header.php';
?>
<div class="resolve-focus-head">
  <div><a class="text-link" href="<?= e($sim?url('simulados.php'):url('questoes.php?concurso='.urlencode((string)$q['concurso']))) ?>">← Voltar</a><div class="resolve-title"><span><?= e(concurso_nome((string)$q['concurso'])) ?> · <?= (int)$q['ano'] ?></span><b><?= e($q['materia']) ?><?= $q['assunto']?' · '.e($q['assunto']):'' ?></b></div></div>
  <div class="question-stopwatch"><small>Tempo nesta questão</small><strong id="questionClock">00:00</strong></div>
</div>

<?php if($sim):?>
<section class="sim-progress-strip"><div class="sim-progress-meta"><b>Simulado #<?= (int)$sim['id'] ?></b><span>Questão <?= $simPos+1 ?> de <?= count($simIds) ?></span></div><div class="sim-palette"><?php foreach($simIds as $i=>$sid):$ans=$simAnswers[$sid]??null;$cls=$i===$simPos?'current':($ans?((int)$ans['avaliavel']?((int)$ans['correta']?'ok':'no'):'answered'):'');?><a class="<?= e($cls) ?>" href="<?= e(url('resolver.php?id='.$sid.'&sim_id='.$simId.'&pos='.$i)) ?>"><?= $i+1 ?></a><?php endforeach;?></div></section>
<?php endif;?>

<div class="card question-shell question-focus" id="questaoBox" data-qid="<?= (int)$q['id'] ?>" data-answered="0" data-simulado="<?= $simId ?>">
  <div class="question-topline"><span class="badge b-gold"><?= e($q['materia']) ?></span><?php if($q['assunto']):?><span class="badge"><?= e($q['assunto']) ?></span><?php endif;?><span class="badge"><?= e($q['dificuldade']) ?></span><?php if($gradable&&(int)$qs['t']>0):?><span class="badge b-blue"><?= (int)round($qs['c']*100/max(1,$qs['t'])) ?>% de acerto</span><?php endif;?></div>
  <div class="enunciado resolve-enunciado"><?= $enunciadoHtml ?></div>
  <?php if($pv):?><figure class="question-origin-preview question-preview" data-question-preview data-pdf="<?= e($pv['url']) ?>" data-page="<?= (int)$pv['page'] ?>" data-y0="<?= e((string)$pv['y0']) ?>" data-y1="<?= e((string)$pv['y1']) ?>"><div class="preview-head"><span>Apoio visual necessário</span><a href="<?= e($pv['url'].'#page='.$pv['page']) ?>" target="_blank" rel="noopener">Abrir fonte</a></div><div class="question-preview-placeholder">Carregando figura/gráfico...</div><canvas hidden></canvas></figure><?php endif;?>
  <div id="feedback"></div>
  <?php if($answerable):?><div class="alts"><?php foreach($alts as $i=>$a):if(trim((string)$a)==='')continue;?><button class="alt" type="button" data-alt="<?= $i ?>"><span class="alt-letter"><?= LETRAS[$i] ?></span><span><?= e($a) ?></span><kbd><?= LETRAS[$i] ?></kbd></button><?php endforeach;?></div><?php endif;?>

  <?php if($uid&&$answerable):?>
    <div class="confidence-box"><span>Antes de corrigir, qual sua confiança?</span><div class="confidence-options"><button type="button" data-confidence="certeza">Certeza</button><button type="button" data-confidence="duvida">Dúvida</button><button type="button" data-confidence="chute">Chute</button></div></div>
    <div class="resolve-submit-row"><button class="btn btn-primary" id="btnResponder" disabled><?= $gradable?'Responder e corrigir':((int)($q['exibir_preview']??0)===1?'Registrar resposta':'Responder e corrigir com IA') ?></button><small class="muted">Atalhos: A–E selecionam · Enter responde</small></div>
  <?php elseif(!$uid&&$answerable):?><p><a class="btn btn-primary" href="<?= e(url('login.php?next='.urlencode($_SERVER['REQUEST_URI']))) ?>">Entre para responder</a></p><?php else:?><div class="flash info" style="display:block">Questão temporariamente sem alternativas textuais confiáveis.</div><?php endif;?>

  <div class="error-classifier" id="errorClassifier" style="display:none"><b>Por que você errou?</b><p>Classificar o erro melhora seu caderno e as próximas recomendações.</p><div><?php foreach(['conteudo'=>'Não sabia o conteúdo','calculo'=>'Erro de cálculo','interpretacao'=>'Interpretação','distracao'=>'Distração','tempo'=>'Falta de tempo','chute'=>'Chute'] as $k=>$v):?><button type="button" class="btn btn-small" data-error-type="<?= e($k) ?>"><?= e($v) ?></button><?php endforeach;?></div></div>

  <div class="resolucao" id="resolucaoBox" style="display:none"><b>Resolução comentada</b><div class="res-body"><p><?= $q['resolucao'] ?></p></div><?php if($uid):?><div class="q-actions"><button class="btn btn-small" id="btnIaQuestao">Pedir outra explicação à Papiro IA</button></div><div class="resolucao" id="iaQuestaoBox" style="display:none;margin-top:10px"></div><?php endif;?></div>

  <?php if($uid):?><div class="resolve-footer-actions"><div><button class="btn btn-small fav-btn <?= $fav?'faved':'' ?>" data-fav="<?= (int)$q['id'] ?>"><?= $fav?'Favoritada':'Favoritar' ?></button><details class="report-inline"><summary>Reportar problema</summary><div class="report-form"><select data-report-type><option value="enunciado">Enunciado</option><option value="alternativas">Alternativas</option><option value="gabarito">Gabarito</option><option value="imagem">Imagem/figura</option><option value="duplicada">Duplicada</option><option value="outro">Outro</option></select><input data-report-detail placeholder="Descreva rapidamente"><button class="btn btn-small" data-report-question="<?= (int)$q['id'] ?>">Enviar</button></div></details></div><div class="grow"></div><?php if($sim&&$prevId):?><a class="btn btn-small" href="<?= e(url('resolver.php?id='.$prevId.'&sim_id='.$simId.'&pos='.($simPos-1))) ?>">Anterior</a><?php endif;?><?php if($nextId):?><a class="btn btn-small btn-primary" id="nextBox" href="<?= e($sim?url('resolver.php?id='.$nextId.'&sim_id='.$simId.'&pos='.($simPos+1)):url('resolver.php?id='.$nextId)) ?>">Próxima</a><?php elseif($sim):?><a class="btn btn-small btn-primary" href="<?= e(url('simulados.php?resultado='.$simId)) ?>">Finalizar e ver resultado</a><?php endif;?></div><?php endif;?>
</div>

<div class="card comments compact-comments"><div class="section-head"><h3>Comentários da comunidade</h3><span class="badge"><?= count($comments) ?></span></div><p class="muted">Use este espaço para compartilhar sua resolução, tirar dúvidas e comparar estratégias com outros usuários.</p><?php if($uid):?><form id="commentForm" data-qid="<?= (int)$q['id'] ?>" class="form"><label>Compartilhe sua resolução ou dúvida<textarea id="commentText" style="min-height:70px" placeholder="Escreva de forma objetiva..."></textarea></label><button class="btn btn-small" type="submit">Publicar</button></form><?php endif;?><div id="commentList"><?php foreach($comments as $c):?><div class="comment"><span class="who"><?= e($c['nome']) ?></span><span class="when"><?= e(fmt_data($c['created_at'])) ?></span><div><?= nl2br(e($c['texto'])) ?></div></div><?php endforeach;?></div></div>
<?php include __DIR__.'/includes/footer.php'; ?>
