<?php
// Gerado automaticamente de data/questoes.js — não editar à mão.
return [
'questoes' => [
['slug'=>'efomm-01','concurso'=>'EFOMM','ano'=>2024,'materia'=>'Matemática','assunto'=>'Trigonometria','dificuldade'=>'Médio',
'enunciado'=>'O valor de <b>sen 75° · cos 15° + cos 75° · sen 15°</b> é igual a:',
'alternativas'=>['1/2','√2/2','√3/2','1','0'],'gabarito'=>3,
'resolucao'=>'Observe que a expressão é da forma <b>sen A·cos B + cos A·sen B = sen(A+B)</b>.<br>Logo: sen 75°·cos 15° + cos 75°·sen 15° = sen(75°+15°) = <b>sen 90° = 1</b>.<br><b>Gabarito: letra D.</b>'],
['slug'=>'efomm-02','concurso'=>'EFOMM','ano'=>2023,'materia'=>'Matemática','assunto'=>'Determinantes','dificuldade'=>'Médio',
'enunciado'=>'Seja A uma matriz quadrada de ordem 3 tal que <b>det(A) = 4</b>. O valor de <b>det(2A)</b> é:',
'alternativas'=>['8','12','16','24','32'],'gabarito'=>4,
'resolucao'=>'Propriedade: <b>det(k·A) = kⁿ · det(A)</b>, onde n é a ordem.<br>det(2A) = 2³ · 4 = 8 · 4 = <b>32</b>.<br><b>Gabarito: letra E.</b>'],
['slug'=>'efomm-03','concurso'=>'EFOMM','ano'=>2024,'materia'=>'Física','assunto'=>'Lançamento oblíquo','dificuldade'=>'Difícil',
'enunciado'=>'Um projétil é lançado do solo com velocidade inicial de <b>20 m/s</b>, formando <b>30°</b> com a horizontal. Despreze a resistência do ar e adote <b>g = 10 m/s²</b>. O alcance horizontal máximo é, em metros:',
'alternativas'=>['10√3','20√3','20','30','40'],'gabarito'=>1,
'resolucao'=>'Alcance: <b>A = v₀² · sen(2θ) / g</b>.<br>A = 20² · sen 60° / 10 = 400 · (√3/2) / 10 = 200√3/10 = <b>20√3 m</b>.<br><b>Gabarito: letra B.</b>'],
['slug'=>'efomm-04','concurso'=>'EFOMM','ano'=>2023,'materia'=>'Física','assunto'=>'Eletrodinâmica','dificuldade'=>'Médio',
'enunciado'=>'Um resistor de <b>20 Ω</b> é percorrido por uma corrente de <b>3 A</b>. A potência dissipada por ele, em watts, é:',
'alternativas'=>['60','120','150','180','240'],'gabarito'=>3,
'resolucao'=>'Potência: <b>P = R · i²</b>.<br>P = 20 · 3² = 20 · 9 = <b>180 W</b>.<br><b>Gabarito: letra D.</b>'],
['slug'=>'efomm-05','concurso'=>'EFOMM','ano'=>2024,'materia'=>'Português','assunto'=>'Interpretação de texto','dificuldade'=>'Fácil',
'enunciado'=>'Assinale a alternativa em que a concordância verbal está de acordo com a norma-padrão:',
'alternativas'=>['Haviam muitos candidatos na sala.','Existe questões difíceis na prova.','Fazem dois anos que estudo para a EFOMM.','Houve mudanças no edital deste ano.','Ocorreu imprevistos durante o exame.'],'gabarito'=>3,
'resolucao'=>'O verbo <b>haver</b> (sentido de existir) e <b>fazer</b> (tempo decorrido) são impessoais: ficam no singular.<br>• \'Haviam\' → errado (correto: Havia). • \'Existe questões\' → errado (Existem). • \'Fazem\' → errado (Faz). • \'Ocorreu imprevistos\' → errado (Ocorreram).<br><b>Correta: \'Houve mudanças no edital\' — letra D.</b>'],
['slug'=>'efomm-06','concurso'=>'EFOMM','ano'=>2024,'materia'=>'Inglês','assunto'=>'Reading comprehension','dificuldade'=>'Médio',
'enunciado'=>'<i>\'Seafarers must comply with safety drills before departure, as negligence may jeopardize the entire crew.\'</i><br>The word <b>\'jeopardize\'</b> can be replaced, without change of meaning, by:',
'alternativas'=>['protect','endanger','ignore','delay','improve'],'gabarito'=>1,
'resolucao'=>'<b>Jeopardize = to put in danger = endanger</b> (pôr em risco).<br>Contexto: negligência pode colocar toda a tripulação em risco.<br><b>Gabarito: letra B.</b>'],
['slug'=>'efomm-07','concurso'=>'EFOMM','ano'=>2022,'materia'=>'Matemática','assunto'=>'Geometria analítica','dificuldade'=>'Médio',
'enunciado'=>'A distância entre o ponto <b>P(3, 4)</b> e a reta <b>3x + 4y − 10 = 0</b> é:',
'alternativas'=>['1','2','3','4','5'],'gabarito'=>2,
'resolucao'=>'Distância ponto-reta: <b>d = |ax₀ + by₀ + c| / √(a²+b²)</b>.<br>d = |3·3 + 4·4 − 10| / √(9+16) = |9+16−10|/5 = 15/5 = <b>3</b>.<br><b>Gabarito: letra C.</b>'],
['slug'=>'efomm-08','concurso'=>'EFOMM','ano'=>2022,'materia'=>'Física','assunto'=>'Hidrostática','dificuldade'=>'Médio',
'enunciado'=>'Um navio desloca <b>5.000 m³</b> de água do mar (densidade <b>1.025 kg/m³</b>). Adote <b>g = 10 m/s²</b>. O empuxo sobre o navio, em newtons, é:',
'alternativas'=>['5,125 × 10⁶','5,125 × 10⁷','5,0 × 10⁶','5,0 × 10⁷','1,025 × 10⁷'],'gabarito'=>1,
'resolucao'=>'Empuxo: <b>E = ρ · V · g</b>.<br>E = 1025 · 5000 · 10 = 1025 · 5×10⁴ = 5,125×10⁷ N.<br><b>Gabarito: letra B.</b>'],
['slug'=>'epcar-01','concurso'=>'EPCAR','ano'=>2024,'materia'=>'Matemática','assunto'=>'Equação do 2º grau','dificuldade'=>'Fácil',
'enunciado'=>'A soma das raízes da equação <b>x² − 7x + 12 = 0</b> é:',
'alternativas'=>['−7','−12','5','7','12'],'gabarito'=>3,
'resolucao'=>'Por Girard: soma = <b>−b/a</b> = −(−7)/1 = <b>7</b>. (Raízes: 3 e 4.)<br><b>Gabarito: letra D.</b>'],
['slug'=>'epcar-02','concurso'=>'EPCAR','ano'=>2023,'materia'=>'Matemática','assunto'=>'Geometria plana','dificuldade'=>'Médio',
'enunciado'=>'Um triângulo retângulo tem catetos <b>6 cm</b> e <b>8 cm</b>. A medida da hipotenusa, em cm, é:',
'alternativas'=>['9','10','12','14','√28'],'gabarito'=>1,
'resolucao'=>'Pitágoras: h² = 6² + 8² = 36 + 64 = 100 → h = <b>10 cm</b>.<br><b>Gabarito: letra B.</b>'],
['slug'=>'epcar-03','concurso'=>'EPCAR','ano'=>2024,'materia'=>'Português','assunto'=>'Morfologia','dificuldade'=>'Fácil',
'enunciado'=>'Na frase <i>\'Os cadetes estudam com dedicação\'</i>, a palavra <b>\'com\'</b> é:',
'alternativas'=>['conjunção','preposição','advérbio','pronome','interjeição'],'gabarito'=>1,
'resolucao'=>'<b>Com</b> liga \'estudam\' a \'dedicação\', estabelecendo relação de modo — é <b>preposição</b>.<br><b>Gabarito: letra B.</b>'],
['slug'=>'epcar-04','concurso'=>'EPCAR','ano'=>2024,'materia'=>'Inglês','assunto'=>'Grammar — Simple Past','dificuldade'=>'Fácil',
'enunciado'=>'Choose the correct sentence:',
'alternativas'=>['She go to school yesterday.','She goed to school yesterday.','She went to school yesterday.','She goes to school yesterday.','She going to school yesterday.'],'gabarito'=>2,
'resolucao'=>'<b>Go</b> é irregular: go → <b>went</b> (past) → gone (participle). Com \'yesterday\' usa-se o simple past.<br><b>Gabarito: letra C.</b>'],
['slug'=>'epcar-05','concurso'=>'EPCAR','ano'=>2024,'materia'=>'Matemática','assunto'=>'Porcentagem','dificuldade'=>'Fácil',
'enunciado'=>'Uma loja oferece <b>20%</b> de desconto em um produto de <b>R$ 250,00</b>. O preço final é:',
'alternativas'=>['R$ 200,00','R$ 205,00','R$ 210,00','R$ 225,00','R$ 230,00'],'gabarito'=>0,
'resolucao'=>'Desconto: 20% de 250 = 0,20 × 250 = 50. Preço final: 250 − 50 = <b>R$ 200,00</b>.<br><b>Gabarito: letra A.</b>'],
['slug'=>'epcar-06','concurso'=>'EPCAR','ano'=>2023,'materia'=>'Matemática','assunto'=>'Radiciação','dificuldade'=>'Médio',
'enunciado'=>'Simplificando <b>√50 + √18 − √8</b>, obtém-se:',
'alternativas'=>['4√2','5√2','6√2','6','2√6'],'gabarito'=>2,
'resolucao'=>'√50 = 5√2; √18 = 3√2; √8 = 2√2.<br>5√2 + 3√2 − 2√2 = <b>6√2</b>.<br><b>Gabarito: letra C.</b>'],
['slug'=>'epcar-07','concurso'=>'EPCAR','ano'=>2023,'materia'=>'Português','assunto'=>'Sintaxe','dificuldade'=>'Médio',
'enunciado'=>'Em <i>\'O instrutor entregou as provas aos alunos\'</i>, a função sintática de <b>\'as provas\'</b> é:',
'alternativas'=>['sujeito','objeto direto','objeto indireto','adjunto adnominal','aposto'],'gabarito'=>1,
'resolucao'=>'\'Entregou\' é transitivo direto e indireto (entregar algo <b>a alguém</b>). \'As provas\' = o que foi entregue → <b>objeto direto</b>; \'aos alunos\' → objeto indireto.<br><b>Gabarito: letra B.</b>'],
['slug'=>'epcar-08','concurso'=>'EPCAR','ano'=>2022,'materia'=>'Inglês','assunto'=>'Vocabulary','dificuldade'=>'Fácil',
'enunciado'=>'The opposite of <b>\'brave\'</b> is:',
'alternativas'=>['courageous','fearless','cowardly','strong','bold'],'gabarito'=>2,
'resolucao'=>'Brave = corajoso. Opostos: <b>cowardly</b> (covarde). As demais são sinônimos.<br><b>Gabarito: letra C.</b>'],
['slug'=>'eear-01','concurso'=>'EEAR','ano'=>2024,'materia'=>'Português','assunto'=>'Concordância nominal','dificuldade'=>'Médio',
'enunciado'=>'Assinale a frase em que a concordância nominal está correta:',
'alternativas'=>['É proibido entrada de estranhos.','É proibida a entrada de estranhos.','Os candidatos mesmo assinaram a lista.','Seguem anexo os documentos.','Haviam bastantes pessoas na fila.'],'gabarito'=>1,
'resolucao'=>'Com artigo definido, \'proibido\' varia: <b>\'É proibida a entrada\'</b>. Sem artigo, fica invariável (\'É proibido entrada\'). \'Mesmo\' como adjunto varia (eles mesmos); \'anexo\' como adjetivo varia (anexos); \'haver\' existencial é impessoal (Havia).<br><b>Gabarito: letra B.</b>'],
['slug'=>'eear-02','concurso'=>'EEAR','ano'=>2024,'materia'=>'Inglês','assunto'=>'Reading','dificuldade'=>'Médio',
'enunciado'=>'<i>\'The sergeant ordered the airmen to double-check the equipment before takeoff.\'</i> According to the sentence, the airmen were told to:',
'alternativas'=>['ignore the equipment','verify the equipment twice','replace the equipment','hide the equipment','sell the equipment'],'gabarito'=>1,
'resolucao'=>'<b>Double-check</b> = conferir duas vezes / verificar com atenção.<br><b>Gabarito: letra B.</b>'],
['slug'=>'eear-03','concurso'=>'EEAR','ano'=>2023,'materia'=>'Matemática','assunto'=>'Progressões','dificuldade'=>'Médio',
'enunciado'=>'Numa PA, o primeiro termo é <b>3</b> e a razão é <b>4</b>. O 10º termo é:',
'alternativas'=>['35','37','39','40','43'],'gabarito'=>2,
'resolucao'=>'Termo geral: aₙ = a₁ + (n−1)·r.<br>a₁₀ = 3 + 9·4 = 3 + 36 = <b>39</b>.<br><b>Gabarito: letra C.</b>'],
['slug'=>'eear-04','concurso'=>'EEAR','ano'=>2023,'materia'=>'Física','assunto'=>'MRU','dificuldade'=>'Fácil',
'enunciado'=>'Uma aeronave voa a <b>900 km/h</b> em MRU. Em <b>20 minutos</b>, a distância percorrida, em km, é:',
'alternativas'=>['150','200','300','450','600'],'gabarito'=>2,
'resolucao'=>'20 min = 1/3 h. d = v·t = 900 × (1/3) = <b>300 km</b>.<br><b>Gabarito: letra C.</b>'],
['slug'=>'eear-05','concurso'=>'EEAR','ano'=>2023,'materia'=>'Português','assunto'=>'Crase','dificuldade'=>'Médio',
'enunciado'=>'Assinale a alternativa em que o uso da crase está correto:',
'alternativas'=>['Chegaremos à noite.','Ele foi à pé para a base.','Estudo à distância há anos.','O relatório foi entregue à oficiais.','A prova começa à uma hora.'],'gabarito'=>0,
'resolucao'=>'Locução adverbial feminina de tempo: <b>\'à noite\'</b> (crase correta). \'A pé\' (palavra masculina) não leva crase; antes de verbo (\'distância\' aqui é verbo? não — mas \'estudo a distância\' sem crase por ser locução com palavra repetida/não determinada... regra prática: não há crase antes de \'distância\' indeterminada); antes de palavra masculina plural sem \'as\' não há crase; antes de hora determinada usa-se crase apenas com artigo: \'à uma hora\' → correto seria \'a uma hora\' (antes de numeral \'uma\' não há crase, salvo \'às uma hora\' em casos específicos).<br><b>Gabarito: letra A.</b>'],
['slug'=>'eear-06','concurso'=>'EEAR','ano'=>2023,'materia'=>'Inglês','assunto'=>'Modal verbs','dificuldade'=>'Fácil',
'enunciado'=>'<i>\'Airmen ___ follow the chain of command at all times.\'</i> Choose the modal that expresses obligation:',
'alternativas'=>['might','could','may','must','would'],'gabarito'=>3,
'resolucao'=>'Obrigação forte: <b>must</b>. (Might/could/may = possibilidade; would = condicional.)<br><b>Gabarito: letra D.</b>'],
['slug'=>'eear-07','concurso'=>'EEAR','ano'=>2024,'materia'=>'Matemática','assunto'=>'Trigonometria','dificuldade'=>'Médio',
'enunciado'=>'Se <b>sen x = 3/5</b> e x pertence ao <b>1º quadrante</b>, então <b>cos x</b> vale:',
'alternativas'=>['−4/5','−3/5','3/4','4/5','5/4'],'gabarito'=>3,
'resolucao'=>'Relação fundamental: sen²x + cos²x = 1 → cos²x = 1 − 9/25 = 16/25 → cos x = ±4/5. No 1º quadrante, cosseno é positivo: <b>4/5</b>.<br><b>Gabarito: letra D.</b>'],
['slug'=>'eear-08','concurso'=>'EEAR','ano'=>2024,'materia'=>'Física','assunto'=>'Calorimetria','dificuldade'=>'Médio',
'enunciado'=>'Para aquecer <b>500 g</b> de água de <b>20 °C</b> até <b>60 °C</b>, sendo o calor específico <b>1 cal/g·°C</b>, a quantidade de calor necessária, em kcal, é:',
'alternativas'=>['10','15','20','25','40'],'gabarito'=>2,
'resolucao'=>'Q = m·c·ΔT = 500 · 1 · (60−20) = 500 · 40 = 20.000 cal = <b>20 kcal</b>.<br><b>Gabarito: letra C.</b>'],
['slug'=>'cn-01','concurso'=>'CN','ano'=>2024,'materia'=>'Matemática','assunto'=>'Produtos notáveis','dificuldade'=>'Fácil',
'enunciado'=>'O valor de <b>(x + 3)² − (x − 3)²</b> é:',
'alternativas'=>['0','6x','12x','18','x² + 9'],'gabarito'=>2,
'resolucao'=>'(x+3)² = x²+6x+9; (x−3)² = x²−6x+9. Subtraindo: 6x−(−6x) = <b>12x</b>.<br><b>Gabarito: letra C.</b>'],
['slug'=>'cn-02','concurso'=>'CN','ano'=>2024,'materia'=>'Matemática','assunto'=>'Geometria plana','dificuldade'=>'Médio',
'enunciado'=>'A soma dos ângulos internos de um <b>octógono regular</b> mede:',
'alternativas'=>['720°','900°','1080°','1260°','1440°'],'gabarito'=>2,
'resolucao'=>'S = (n−2)·180° = (8−2)·180° = 6·180° = <b>1080°</b>.<br><b>Gabarito: letra C.</b>'],
['slug'=>'cn-03','concurso'=>'CN','ano'=>2024,'materia'=>'Português','assunto'=>'Interpretação','dificuldade'=>'Fácil',
'enunciado'=>'Em <i>\'O mar, calmo e imenso, convidava os marinheiros à aventura\'</i>, a expressão destacada por vírgulas exerce a função de:',
'alternativas'=>['vocativo','aposto','adjunto adverbial','sujeito','predicativo'],'gabarito'=>1,
'resolucao'=>'\'Calmo e imenso\' explica/caracteriza \'o mar\' — termo explicativo = <b>aposto</b>.<br><b>Gabarito: letra B.</b>'],
['slug'=>'cn-04','concurso'=>'CN','ano'=>2024,'materia'=>'Inglês','assunto'=>'Reading','dificuldade'=>'Fácil',
'enunciado'=>'<i>\'Brazil\'s Navy protects over 7,000 km of coastline.\'</i> The sentence is in the:',
'alternativas'=>['simple past','present perfect','simple present','future','past continuous'],'gabarito'=>2,
'resolucao'=>'\'Protects\' (verbo + s, 3ª pessoa) indica hábito/fato → <b>simple present</b>.<br><b>Gabarito: letra C.</b>'],
['slug'=>'cn-05','concurso'=>'CN','ano'=>2023,'materia'=>'Matemática','assunto'=>'Sistemas lineares','dificuldade'=>'Médio',
'enunciado'=>'A solução do sistema <b>{ x + y = 10; x − y = 4 }</b> é:',
'alternativas'=>['x=3, y=7','x=7, y=3','x=5, y=5','x=6, y=2','x=4, y=6'],'gabarito'=>1,
'resolucao'=>'Somando as equações: 2x = 14 → x = 7. Substituindo: 7 + y = 10 → y = 3.<br><b>Gabarito: letra B.</b>'],
['slug'=>'cn-06','concurso'=>'CN','ano'=>2023,'materia'=>'Ciências','assunto'=>'Física — Densidade','dificuldade'=>'Fácil',
'enunciado'=>'Um bloco de <b>200 g</b> ocupa um volume de <b>50 cm³</b>. Sua densidade, em g/cm³, é:',
'alternativas'=>['2','3','4','5','10'],'gabarito'=>2,
'resolucao'=>'d = m/V = 200/50 = <b>4 g/cm³</b>.<br><b>Gabarito: letra C.</b>'],
['slug'=>'cn-07','concurso'=>'CN','ano'=>2023,'materia'=>'Matemática','assunto'=>'MMC e MDC','dificuldade'=>'Médio',
'enunciado'=>'O MMC entre <b>12, 18 e 30</b> é:',
'alternativas'=>['60','90','120','180','360'],'gabarito'=>3,
'resolucao'=>'12 = 2²·3; 18 = 2·3²; 30 = 2·3·5. MMC = 2²·3²·5 = 4·9·5 = <b>180</b>.<br><b>Gabarito: letra D.</b>'],
['slug'=>'cn-08','concurso'=>'CN','ano'=>2022,'materia'=>'Português','assunto'=>'Pontuação','dificuldade'=>'Fácil',
'enunciado'=>'Assinale a frase pontuada corretamente:',
'alternativas'=>['Os alunos, estudaram muito para a prova.','Os alunos estudaram muito, para a prova.','Os alunos estudaram muito para a prova.','Os alunos, estudaram, muito para a prova.','Os, alunos estudaram muito para a prova.'],'gabarito'=>2,
'resolucao'=>'Não se separa sujeito do verbo nem verbo de seu complemento por vírgula. Frase direta, sem adjuntos deslocados → <b>sem vírgulas</b>.<br><b>Gabarito: letra C.</b>'],
['slug'=>'ita-01','concurso'=>'ITA','ano'=>2024,'materia'=>'Matemática','assunto'=>'Números complexos','dificuldade'=>'Difícil',
'enunciado'=>'Se <b>z = 1 + i</b>, então <b>z¹⁰</b> é igual a:',
'alternativas'=>['32i','−32i','32','−32','16 + 16i'],'gabarito'=>0,
'resolucao'=>'Forma polar: z = √2·(cos 45° + i·sen 45°). Por De Moivre: z¹⁰ = (√2)¹⁰·(cos 450° + i·sen 450°) = 32·(cos 90° + i·sen 90°) = 32·(0 + i) = <b>32i</b>.<br><b>Gabarito: letra A.</b>'],
['slug'=>'ita-02','concurso'=>'ITA','ano'=>2023,'materia'=>'Matemática','assunto'=>'Polinômios','dificuldade'=>'Difícil',
'enunciado'=>'O resto da divisão de <b>P(x) = x³ − 2x² + x − 1</b> por <b>(x − 1)</b> é:',
'alternativas'=>['−2','−1','0','1','2'],'gabarito'=>1,
'resolucao'=>'Teorema do resto: R = P(1) = 1 − 2 + 1 − 1 = <b>−1</b>.<br><b>Gabarito: letra B.</b>'],
['slug'=>'ita-03','concurso'=>'ITA','ano'=>2024,'materia'=>'Física','assunto'=>'Dinâmica','dificuldade'=>'Difícil',
'enunciado'=>'Um bloco de <b>2 kg</b> sobre plano horizontal sem atrito é puxado por força de <b>10 N</b> que forma <b>60°</b> com a horizontal. A aceleração horizontal do bloco, em m/s², é:',
'alternativas'=>['1,0','2,0','2,5','5,0','8,7'],'gabarito'=>2,
'resolucao'=>'Componente horizontal: Fx = F·cos 60° = 10 · 0,5 = 5 N. 2ª lei: a = F/m = 5/2 = <b>2,5 m/s²</b>.<br><b>Gabarito: letra C.</b>'],
['slug'=>'ita-04','concurso'=>'ITA','ano'=>2023,'materia'=>'Física','assunto'=>'Óptica','dificuldade'=>'Médio',
'enunciado'=>'Um objeto está a <b>30 cm</b> de um espelho plano. A distância entre o objeto e sua imagem é:',
'alternativas'=>['15 cm','30 cm','45 cm','60 cm','90 cm'],'gabarito'=>3,
'resolucao'=>'No espelho plano, a imagem é simétrica: forma-se a 30 cm \'atrás\' do espelho. Distância objeto–imagem = 30 + 30 = <b>60 cm</b>.<br><b>Gabarito: letra D.</b>'],
['slug'=>'ita-05','concurso'=>'ITA','ano'=>2024,'materia'=>'Química','assunto'=>'Estequiometria','dificuldade'=>'Médio',
'enunciado'=>'Na combustão completa do metano (<b>CH₄ + 2O₂ → CO₂ + 2H₂O</b>), a massa de CO₂ produzida a partir de <b>32 g</b> de CH₄ é: (massas molares: CH₄ = 16 g/mol; CO₂ = 44 g/mol)',
'alternativas'=>['22 g','32 g','44 g','66 g','88 g'],'gabarito'=>4,
'resolucao'=>'32 g de CH₄ = 2 mol. Proporção 1:1 com CO₂ → 2 mol de CO₂ = 2 × 44 = <b>88 g</b>.<br><b>Gabarito: letra E.</b>'],
['slug'=>'ita-06','concurso'=>'ITA','ano'=>2024,'materia'=>'Português','assunto'=>'Figuras de linguagem','dificuldade'=>'Médio',
'enunciado'=>'Em <i>\'Ele tem um coração de pedra\'</i>, a figura de linguagem presente é:',
'alternativas'=>['hipérbole','eufemismo','ironia','metáfora','aliteração'],'gabarito'=>3,
'resolucao'=>'Comparação implícita (coração = pedra, pela dureza) sem conectivo → <b>metáfora</b>.<br><b>Gabarito: letra D.</b>'],
['slug'=>'ita-07','concurso'=>'ITA','ano'=>2024,'materia'=>'Inglês','assunto'=>'Reading — inference','dificuldade'=>'Difícil',
'enunciado'=>'<i>\'Although the experiment yielded inconclusive results, the data hinted at a correlation that warrants further investigation.\'</i> It can be inferred that:',
'alternativas'=>['the experiment was a complete failure','no correlation exists','more research is needed','the data was fabricated','the hypothesis was confirmed'],'gabarito'=>2,
'resolucao'=>'\'Warrants further investigation\' = merece investigação adicional → <b>more research is needed</b>.<br><b>Gabarito: letra C.</b>'],
['slug'=>'ita-08','concurso'=>'ITA','ano'=>2024,'materia'=>'Matemática','assunto'=>'Análise combinatória','dificuldade'=>'Difícil',
'enunciado'=>'De quantas formas <b>5 pessoas</b> podem se sentar em fila se <b>duas delas (A e B) devem ficar juntas</b>?',
'alternativas'=>['24','48','60','72','120'],'gabarito'=>1,
'resolucao'=>'Trate AB como um bloco: 4 \'objetos\' → 4! = 24. Dentro do bloco, A e B permutam: 2! = 2. Total: 24 × 2 = <b>48</b>.<br><b>Gabarito: letra B.</b>'],
['slug'=>'esa-01','concurso'=>'ESA','ano'=>2024,'materia'=>'Matemática','assunto'=>'Função afim','dificuldade'=>'Fácil',
'enunciado'=>'Se <b>f(x) = 3x − 5</b>, então <b>f(4)</b> vale:',
'alternativas'=>['5','6','7','9','12'],'gabarito'=>2,
'resolucao'=>'f(4) = 3·4 − 5 = 12 − 5 = <b>7</b>.<br><b>Gabarito: letra C.</b>'],
['slug'=>'esa-02','concurso'=>'ESA','ano'=>2024,'materia'=>'Português','assunto'=>'Classes de palavras','dificuldade'=>'Fácil',
'enunciado'=>'Em <i>\'O soldado brasileiro é disciplinado\'</i>, a palavra <b>\'brasileiro\'</b> é:',
'alternativas'=>['substantivo','adjetivo','advérbio','verbo','pronome'],'gabarito'=>1,
'resolucao'=>'\'Brasileiro\' caracteriza o substantivo \'soldado\' → <b>adjetivo</b>.<br><b>Gabarito: letra B.</b>'],
['slug'=>'espcex-01','concurso'=>'EsPCEx','ano'=>2024,'materia'=>'Matemática','assunto'=>'Logaritmos','dificuldade'=>'Médio',
'enunciado'=>'O valor de <b>log₂ 32</b> é:',
'alternativas'=>['4','5','6','8','16'],'gabarito'=>1,
'resolucao'=>'log₂ 32 = x → 2ˣ = 32 = 2⁵ → x = <b>5</b>.<br><b>Gabarito: letra B.</b>'],
['slug'=>'espcex-02','concurso'=>'EsPCEx','ano'=>2024,'materia'=>'Física','assunto'=>'MUV','dificuldade'=>'Médio',
'enunciado'=>'Um móvel parte do repouso com aceleração de <b>2 m/s²</b>. Após <b>5 s</b>, sua velocidade, em m/s, é:',
'alternativas'=>['5','7','10','12','25'],'gabarito'=>2,
'resolucao'=>'v = v₀ + at = 0 + 2·5 = <b>10 m/s</b>.<br><b>Gabarito: letra C.</b>'],
['slug'=>'afa-01','concurso'=>'AFA','ano'=>2024,'materia'=>'Matemática','assunto'=>'Matrizes','dificuldade'=>'Médio',
'enunciado'=>'Se <b>A = [[1,2],[3,4]]</b>, então <b>det(A)</b> vale:',
'alternativas'=>['−2','−1','2','5','10'],'gabarito'=>0,
'resolucao'=>'det = 1·4 − 2·3 = 4 − 6 = <b>−2</b>.<br><b>Gabarito: letra A.</b>'],
['slug'=>'afa-02','concurso'=>'AFA','ano'=>2024,'materia'=>'Inglês','assunto'=>'Grammar','dificuldade'=>'Médio',
'enunciado'=>'<i>\'The pilot ___ flying for ten years.\'</i> Complete with the present perfect continuous:',
'alternativas'=>['has been','have been','is','was','will be'],'gabarito'=>0,
'resolucao'=>'3ª pessoa singular → <b>has been flying</b>.<br><b>Gabarito: letra A.</b>'],
['slug'=>'ime-01','concurso'=>'IME','ano'=>2024,'materia'=>'Matemática','assunto'=>'Binômio de Newton','dificuldade'=>'Difícil',
'enunciado'=>'O coeficiente de <b>x²</b> no desenvolvimento de <b>(x + 2)⁴</b> é:',
'alternativas'=>['8','12','16','24','32'],'gabarito'=>3,
'resolucao'=>'Termo geral: C(4,k)·x^(4−k)·2ᵏ. Para x²: k=2 → C(4,2)·2² = 6·4 = <b>24</b>.<br><b>Gabarito: letra D.</b>'],
['slug'=>'ime-02','concurso'=>'IME','ano'=>2023,'materia'=>'Química','assunto'=>'Soluções','dificuldade'=>'Médio',
'enunciado'=>'A concentração, em g/L, de uma solução com <b>20 g</b> de soluto em <b>500 mL</b> é:',
'alternativas'=>['10','20','30','40','50'],'gabarito'=>3,
'resolucao'=>'500 mL = 0,5 L. C = 20/0,5 = <b>40 g/L</b>.<br><b>Gabarito: letra D.</b>'],
['slug'=>'cfn-01','concurso'=>'CFN','ano'=>2024,'materia'=>'Matemática','assunto'=>'Regra de três','dificuldade'=>'Fácil',
'enunciado'=>'Se <b>4 marinheiros</b> pintam um compartimento em <b>6 horas</b>, em quanto tempo <b>8 marinheiros</b> (mesmo ritmo) pintam o mesmo compartimento?',
'alternativas'=>['2 h','3 h','4 h','8 h','12 h'],'gabarito'=>1,
'resolucao'=>'Grandezas inversamente proporcionais: dobrou a equipe → cai pela metade o tempo: <b>3 h</b>.<br><b>Gabarito: letra B.</b>'],
['slug'=>'cfn-02','concurso'=>'CFN','ano'=>2024,'materia'=>'Português','assunto'=>'Ortografia','dificuldade'=>'Fácil',
'enunciado'=>'Assinale a palavra grafada corretamente:',
'alternativas'=>['excessão','exceção','eccessão','exceçâo','execção'],'gabarito'=>1,
'resolucao'=>'O correto é <b>exceção</b> (com \'ç\').<br><b>Gabarito: letra B.</b>'],
],
'trilhas' => [
['slug'=>'efomm','nome'=>'EFOMM','icone'=>'⚓','cor'=>'#1E5AA8','modulos'=>['Matemática Básica','Funções & Trigonometria','Geometria','Física I — Mecânica','Física II — Eletricidade','Português','Inglês','Simulados finais']],
['slug'=>'epcar','nome'=>'EPCAR','icone'=>'✈️','cor'=>'#0E7C5B','modulos'=>['Aritmética','Álgebra','Geometria Plana','Português Total','Inglês Total','Revisão + Simulados']],
['slug'=>'eear','nome'=>'EEAR','icone'=>'🛩️','cor'=>'#7B3FA4','modulos'=>['Português (Gramática)','Inglês','Matemática','Física','Baterias de questões']],
['slug'=>'cn','nome'=>'Colégio Naval','icone'=>'🧭','cor'=>'#C25700','modulos'=>['Matemática Fundamental','Álgebra','Geometria','Português','Inglês','Ciências','Simulados CN']],
['slug'=>'ita','nome'=>'ITA','icone'=>'🚀','cor'=>'#B00020','modulos'=>['Matemática Avançada','Física Avançada','Química','Português & Redação','Inglês Avançado','Provas antigas comentadas']],
['slug'=>'base','nome'=>'Base Forte em Matemática','icone'=>'📐','cor'=>'#8A6D00','modulos'=>['Operações & Frações','Potências & Raízes','Equações','Porcentagem & Proporção','Geometria básica','Funções']],
],
'guia' => [
['slug'=>'mat','titulo'=>'Como estudar Matemática','icone'=>'📐','tempo'=>'8 min','texto'=>'<b>1. Teoria mínima, questão máxima.</b> Para cada tópico, estude o conceito em 20–30 min e resolva 15–25 questões.<br><b>2. Caderno de erros.</b> Toda questão errada entra no caderno com o motivo: conceito, conta ou interpretação.<br><b>3. Revisão espaçada.</b> Revise em 24h, 7 dias e 30 dias.<br><b>4. Base forte.</b> 80% dos erros em concursos militares vêm de frações, potências e equações — domine a trilha Base Forte antes de avançar.'],
['slug'=>'fis','titulo'=>'Como estudar Física','icone'=>'⚛️','tempo'=>'7 min','texto'=>'<b>1. Entenda antes de decorar.</b> Física cobra aplicação de leis (Newton, conservação de energia). Desenhe o problema.<br><b>2. Liste as fórmulas por assunto</b> e refaça as deduções principais.<br><b>3. Questões por nível:</b> comece pela EEAR/EPCAR e suba para EFOMM/ITA.<br><b>4. Unidades importam:</b> confira sempre m/s × km/h, cal × joule.'],
['slug'=>'rev','titulo'=>'Revisão','icone'=>'🔁','tempo'=>'5 min','texto'=>'Use o ciclo <b>24h → 7d → 30d</b>. Revisão não é reler: é <b>refazer questões</b> sem olhar a resolução. Marque no app as questões para revisar e use o modo Revisão do Caderno de Erros.'],
['slug'=>'erros','titulo'=>'Caderno de erros','icone'=>'📓','tempo'=>'6 min','texto'=>'Para cada erro registre: <b>(a)</b> o que a questão pedia, <b>(b)</b> por que você errou, <b>(c)</b> a forma correta em 2 linhas. Releia o caderno toda semana antes do simulado. No Papiro Máximo, erros vão automaticamente para o Caderno.'],
['slug'=>'sim','titulo'=>'Simulados','icone'=>'⏱️','tempo'=>'6 min','texto'=>'<b>1 por semana</b>, no horário da prova, sem pausa e sem celular. Corrija no mesmo dia e jogue os erros no caderno. Acompanhe a taxa de acerto no Início — meta: <b>70%+</b> no seu concurso-alvo.'],
['slug'=>'recall','titulo'=>'Active Recall','icone'=>'🧠','tempo'=>'5 min','texto'=>'Feche o material e tente explicar o tópico em voz alta. Se travar, é ali que está a lacuna. Em questões: cubra o gabarito e force a resposta antes de confirmar. O esforço de lembrar é o que fixa.'],
['slug'=>'org','titulo'=>'Organização semanal','icone'=>'🗓️','tempo'=>'6 min','texto'=>'Modelo sugerido (2h/dia): <b>Seg/Qua/Sex</b> — Matemática + questões; <b>Ter/Qui</b> — Física + Português/Inglês alternados; <b>Sáb</b> — simulado + correção; <b>Dom</b> — revisão leve + caderno de erros. Registre as horas no timer do Início para manter a ofensiva.'],
],
];
